### ISSUE TITLE
[Feature] split rails command into different rail types

### ISSUE THREAD

**Issue by Agrrox** [oganexon/BTE-tools#15]
Currently the `/cs rails` command handles all types of railways, (etc. trains trams, and subways). On very complex sections like stations or crossings there might be some overlaps that can cause issues while building or implementing railways into already build areas.

 I suggest ability to use: (notice: the syntax is just example to explain for what i mean)
-  individual train type (example: `/cs railway=subway <args>`)
- combination of types in single command (example: `/cs railway=subway <args>,railway=trams <args>`)
- commands that differentiate between rails, trams and subways (example: `/cs rails <args>` `/cs subway <args>` `/cs tram <args>`)

**this is just and idea, the syntax is just example and it may not be correct to be that way, its not final and I would like to hear feedback, if this would work in practice,**

 https://wiki.openstreetmap.org/wiki/Key:railway:

**Comment by oganexon** [comment]
Now you can use any key to select rail type:
```sh
/cs rails {"regex":"(subway|tram)"}
```

Any key works. (https://wiki.openstreetmap.org/wiki/Key:railway)

Default regex is "^.*$" (any rail type)
