### ISSUE TITLE
[Feature] cs rails u add argument to set specific height of rails

### ISSUE THREAD

**Issue by Agrrox** [oganexon/BTE-tools#16]
is there a way to set specific height up with command `/cs rails region u`?
For example I'm building a metro and I want outlines in the area that is already full of buildings so parsing data there with block height of 0 or 1 is not practical. what about being able to have option to set heigh option? (50 blocks above surface, -20 blocks bellow surface)

**Comment by oganexon** [comment]
Here's how the new syntax looks:

To draw 50 blocks above surface
```sh
/cs rails {"offset":50}
```

To draw at the y level of your feets:
```sh
/cs rails {"onGround":false}
```

Be careful, the height option corresponds to the height of a wall `{"height":50}`
The next version should be out soon 😉
