### ISSUE TITLE
Bring back regionEdge option

### ISSUE THREAD

**Issue by oganexon** [oganexon/BTE-tools#29]
**Is your feature request related to a problem? Please describe.**
Before v2.0.0, we had the ability to restrict the range of action of the `rails` and `hedges` commands to our selection. (This was previously knows as `/cs rails regionEdge` and `/cs hedges regionEdge`)
It was very handy for not drawing lines over large areas.

**Describe the solution you'd like**
Add an option in the JSON object of the different commands to do so: `rails`, `railsnear`, `hedges`, and `hedgesnear`.
Examples that might be suitable
```
/cs rails {"restrict":true}
/cs rails {"edges":true}
```

**Additional context**
The function that was responsible for this behavior can be found here  https://github.com/oganexon/BTE-tools/blob/9a02c4d232a0ba043f6c1ffb49a387c7bc7014d2/src/modules/drawLines.js#L48-L54

This should be easy for the `rails` and `hedges` commands as the region is already selected by the user.
For `railsnear` and `hedgesnear` it will be harder since a new region has to be created from code (cylindrical I think).

**Comment by TjhVarga** [comment]
On It

**Comment by oganexon** [comment]
Added in v2.1.0
